app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_contact:
    path:     /contact
    defaults: { _controller: AppBundle:Default:contact }

app_validation:
    path:     /contact/message-envoye
    defaults: { _controller: AppBundle:Default:validation }
